== Tst
This is a collection of bash scripts that help you easily test lines of code
without having to create new files and directories. For compiled code, it allows
you to step into the code with gdb by adding debuging symbols. Everything is
integrated with vim.

=== Installation
To install for the current user do

----
sudo make install USER=$USER
----

Otherwise you can change `$USER` to whatever user you want to use the scripts as

=== Running
This command will open up vim into the default template for you language

[source ,sh]
----
$ tst <language exention> <template>
----

if no template is specified then the default template will be used

You can edit /usr/local/bin/runtst to modify how your program runs. This might
be a good place to check if your program does not run.

=== Vim commands
[%header, rows=1,1]
|===
| Command    | action
| `<leader>rt` | runs the program in split terminal
| `<leader>rg` | runs gdb in split terminal
|===

If you do not like these command mappings you can change them in the
_/usr/local/share/tst/commands.vim_ file.

=== Templates
Templates are located in _/usr/local/share/tst/templates/_. Just look for your
language and then and then the _default_ file. This file will be the default
template when you run tst. Otherwise you can look for or make a specific
template in this directory.

== GDB
You can specifiy a specific gdb configuration for you language by changing
_/usr/local/share/tst/gdb/<language>.gdb_. Where language is the language you
wish to add a configuration for. If you want to change the gdb configuration for
all languages then edit the _/usr/local/share/tst/gdb/global.gdb_ file.

== Supported languages
- c
- javascript
- lua
- nasm
- perl
- python

== Dependencies
- nasm
- gcc
- Interpreter for you're language
